# Generated by Django 2.2.5 on 2021-02-09 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_auto_20210209_1352'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tuser',
        ),
    ]
