# Generated by Django 2.2.5 on 2021-02-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_delete_tuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='gu',
            name='gu_locx',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gu',
            name='gu_locy',
            field=models.IntegerField(default=0),
        ),
    ]
